### ISSUE TITLE
Error in recognition Q and O

### ISSUE THREAD

**Issue by AnteaterKit** [andreluizsecco/RecogCaptcha#3]
How i can fix it?
There is a "POLL" at picture, but Captcha show PQLL
![b9a9b078-e19c-461d-8b41-3c9502e0f801](https://user-images.githubusercontent.com/5115677/37684145-1b7f79e4-2ca0-11e8-96ed-5f76534e8265.jpeg)
<img width="289" alt="screen shot 2018-03-21 at 00 40 32" src="https://user-images.githubusercontent.com/5115677/37684259-81887736-2ca0-11e8-896b-0b4be29f8ddf.png">

**Comment by andreluizsecco** [comment]
Hello @AnteaterKit, the code is not generic. It is necessary to implement specific filters with AForge.NET to meet specifically the types of captcha.
In your case, need it change the AForge.NET filters or remove it (because your image is not "dirty").

Change the full content of "reconhecerCaptcha" method (Form1.cs), for this:

```csharp
Bitmap imagem = new Bitmap(img);
imagem = imagem.Clone(new Rectangle(0, 0, img.Width, img.Height), System.Drawing.Imaging.PixelFormat.Format24bppRgb);
Erosion erosion = new Erosion();
Dilatation dilatation = new Dilatation();
Invert inverter = new Invert();
ColorFiltering cor = new ColorFiltering();
cor.Blue = new AForge.IntRange(200, 255);
cor.Red = new AForge.IntRange(200, 255);
cor.Green = new AForge.IntRange(200, 255);
Opening open = new Opening();
BlobsFiltering bc = new BlobsFiltering();
Closing close = new Closing();
GaussianSharpen gs = new GaussianSharpen();
ContrastCorrection cc = new ContrastCorrection();
bc.MinHeight = 10;
pictureBox.Image = imagem;
string reconhecido = OCR((Bitmap)pictureBox.Image);
return reconhecido;
```
Note, I changed only filters, removing this line:
```csharp
FiltersSequence seq = new FiltersSequence(gs, inverter, open, inverter, bc, inverter, open, cc, cor, bc, inverter);
```
Try again with this changes and let me know your result.

**Comment by AnteaterKit** [comment]
Hello!
Thank you! It's help for me.
